# Generated by Django 4.2.8 on 2025-01-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_parts_store', '0002_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='price_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
