version: '3.9'
services:
  frontend:
    image: jokeswar/ims-front:latest
    depends_on:
      - backend
    ports:
      - 5173:5173
  backend:
    image: jokeswar/ims:latest
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - STRIPE_SECRET_KEY=key
    ports:
      - 8000:8000
  postgres:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=computer_parts_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
