export { default as HomeView } from './HomeView.vue';
export { default as LoginView } from './LoginView.vue';
export { default as RegisterView } from './RegisterView.vue';
export { default as ProductView } from './ProductView.vue';
export { default as AddProductView } from './AddProductView.vue';
export { default as ProfileView } from './ProfileView.vue';
export { default as AboutView } from './AboutView.vue';
export { default as CartView } from './CartView.vue';
export { default as CheckoutView } from './CheckoutView.vue';